### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by typeshige** [mklymyshyn/django-dtpanel-htmltidy#1]
I think I have it installed correctly but I get this error:

```
OSError at /

Could not load libtidy using any of these names: libtidy,libtidy.so,libtidy-0.99.so.0,cygtidy-0-99-0,tidylib,libtidy.dylib,tidy
```

I have:

pytidylib==0.2.1
Django==1.3

debug toolbar is the latest from Github.

Thanks,
Shige

**Comment by mklymyshyn** [comment]
I guess it's OS-related issue so please provide:
1. Your OS and version
2. Your LD_LIBRARY_PATH environment variable

Maybe pytidylib require some libtidy-dev or something like that.

**Comment by camilonova** [comment]
I have this error too, you must tell in the docs that you need to install the package:

```
libtidy-dev
```

Thanks

**Comment by mklymyshyn** [comment]
Thank you camilonova, I've updated docs.
